/**
 * memoService — AI Investment Memo Generator
 *
 * Generates a polished, structured investment memo from top-scored categories.
 * Useful for: sharing with co-founders, investor decks, internal decision-making.
 *
 * One Gemini call, ~€0.01–0.03 depending on context size.
 */

import { GoogleGenAI } from '@google/genai';
import { getApiKey, checkBudget, recordGeminiUsageFromResponse } from '../lib/settings';
import type { Category, Weights, BrainEntry } from '../types';
import { calculateDecisionScore, calculateLtvCac } from '../utils';
import { compileDirectivePrompt } from '../lib/directives';

export async function generateInvestmentMemo(
  categories: Category[],
  weights: Weights,
  maxClv: number,
  brainEntries: BrainEntry[] = [],
): Promise<string> {
  const apiKey = getApiKey();
  if (!apiKey) throw new Error('Gemini API key not set');
  checkBudget();

  const scored = categories
    .filter(c => c.status !== 'Killed')
    .map(c => ({ ...c, score: calculateDecisionScore(c, weights, maxClv), ltvCac: calculateLtvCac(c.estimatedCLV, c.estimatedCAC) }))
    .sort((a, b) => b.score - a.score)
    .slice(0, 5);

  const winner = scored.find(c => c.status === 'Winner') || scored[0];

  const categoryData = scored.map((c, i) => `
### ${i + 1}. ${c.name} [Score: ${c.score.toFixed(1)} | LTV:CAC: ${c.ltvCac}x | Status: ${c.status}]
- CLV: €${c.estimatedCLV} | CAC: €${c.estimatedCAC} | Monthly Churn: ${c.monthlyChurnPercent}%
- Market (NL): ${c.marketSizeNL || 'Unknown'} | TAM: ${c.tamNL ? `€${c.tamNL.toLocaleString()}` : '?'} | SAM: ${c.samNL ? `€${c.samNL.toLocaleString()}` : '?'} | SOM: ${c.somNL ? `€${c.somNL.toLocaleString()}` : '?'}
- Acquisition: ${c.acquisitionDifficulty} | Loyalty: ${c.emotionalLoyalty} | CAGR: ${c.cagr || '?'}
- Regulatory Risk: ${c.regulatoryRiskNL || '?'} | Target: ${c.targetAudience}
${c.agentResults?.marketDynamics ? `- Market Intelligence: ${c.agentResults.marketDynamics.slice(0, 400)}` : ''}
${c.notes ? `- Notes: ${c.notes.slice(0, 300)}` : ''}`).join('\n');

  const ai = new GoogleGenAI({ apiKey });
  const directiveBlock = compileDirectivePrompt(brainEntries, 'memo');

  const prompt = `${directiveBlock}You are a senior investment analyst at a top-tier European PE firm specializing in D2C subscription businesses.

Generate a concise, professional investment memo for a Dutch DTC subscription founder evaluating the following top-scored categories. The founder is deciding where to invest their first €100K to build a scalable subscription business in the Netherlands.

**CATEGORY DATA (AI-researched):**
${categoryData}

**Format the memo as follows (use markdown headings):**

# Investment Memo — Category Selection
*Netherlands DTC Subscription | ${new Date().toLocaleDateString('en-NL', { month: 'long', year: 'numeric' })}*

## Executive Summary
[2-3 sentences: current winner recommendation + key rationale]

## Recommended Category: ${winner.name}
### Investment Thesis
[3-4 bullet points on WHY this category wins. Reference actual numbers from the data.]

### Unit Economics
[Table with CLV, CAC, LTV:CAC, Monthly Churn, Implied Payback Period for the top 2 categories]

### Market Opportunity (NL)
[TAM → SAM → SOM for the winning category. Commentary on CAGR and timing.]

### Key Risks
[3 risks specific to the winning category, each with a mitigation note]

## Runner-Up Analysis
### ${scored[1]?.name || 'N/A'}
[2-3 sentences: why it's #2 and what would change the conviction]

## Decision Framework
[1 paragraph: what the founder should validate in the next 30 days before committing]

## Kill Signal Criteria
[3 bullets: specific data points that would make you abandon the winning category]

---
*Generated by FlashFace OS | AI-assisted analysis, not financial advice*

Write with the confidence of a PE analyst. Be specific with numbers. Use crisp, direct language. Avoid fluff.`;

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash',
    contents: [{ role: 'user', parts: [{ text: prompt }] }],
    config: { temperature: 0.4 },
  });

  recordGeminiUsageFromResponse({
    model: 'gemini-2.5-flash',
    contents: [{ role: 'user', parts: [{ text: prompt }] }],
    config: { temperature: 0.4 },
  }, response, {
    feature: 'investment-memo',
    operation: 'memo-generation',
    model: 'gemini-2.5-flash',
  });

  return response.candidates?.[0]?.content?.parts?.[0]?.text ?? 'No memo generated';
}
