import { Category } from './types';

export const INITIAL_WEIGHTS = {
  clv: 30,
  retention: 25,
  acquisition: 20,
  marketSize: 15,
  loyalty: 10,
  storyDepth: 8,
  microNiche: 7,
};

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: '1',
    name: 'Premium Pet Supplements (Joint Care)',
    targetAudience: 'Millennial/Gen X Dog Owners',
    realMonthlyConsumption: true,
    monthlyConsumptionReason: 'Daily chew supplement to prevent/treat arthritis',
    estimatedCLV: 240,
    estimatedCAC: 35,
    monthlyChurnPercent: 12,
    marketSizeNL: '1.5M Dogs in NL',
    marketSizeScore: 65,
    acquisitionDifficulty: 'Medium',
    emotionalLoyalty: 'High',
    storyDepth: 8,
    brandType: 'Solution-based',
    microNichePotential: 9,
    awarenessLevel: 'Problem-aware',
    status: 'Winner',
    lastUpdated: new Date().toISOString(),
    notes: 'Strong recurring revenue. People will spend anything on their pets if they see them suffering. High LTV if product works.'
  },
  {
    id: '2',
    name: 'Functional Mushroom Coffee (Women)',
    targetAudience: 'Health-conscious Women 25-45',
    realMonthlyConsumption: true,
    monthlyConsumptionReason: 'Daily morning ritual replacement',
    estimatedCLV: 180,
    estimatedCAC: 45,
    monthlyChurnPercent: 18,
    marketSizeNL: '750k Target Demo',
    marketSizeScore: 40,
    acquisitionDifficulty: 'Hard',
    emotionalLoyalty: 'Medium',
    storyDepth: 7,
    brandType: 'Aesthetic-Pleasure',
    microNichePotential: 8,
    awarenessLevel: 'Solution-aware',
    status: 'Researching',
    lastUpdated: new Date().toISOString(),
    notes: 'High CAC due to competition from Mud/Wtr etc. Needs strong brand differentiation.'
  },
  {
    id: '3',
    name: 'AG1-style Greens Powder',
    targetAudience: 'High-performers, Biohackers',
    realMonthlyConsumption: true,
    monthlyConsumptionReason: 'Daily vitamin/nutrient baseline',
    estimatedCLV: 350,
    estimatedCAC: 80,
    monthlyChurnPercent: 15,
    marketSizeNL: '500k Target Demo',
    marketSizeScore: 35,
    acquisitionDifficulty: 'Hard',
    emotionalLoyalty: 'Medium',
    storyDepth: 6,
    brandType: 'Solution-based',
    microNichePotential: 5,
    awarenessLevel: 'Product-aware',
    status: 'Killed',
    lastUpdated: new Date().toISOString(),
    notes: 'Too saturated. The big players spend millions on podcasts. Hard to break in without massive capital.'
  },
  {
    id: '4',
    name: 'Daily Barrier Cream',
    targetAudience: 'Women 18-35 with sensitive skin',
    realMonthlyConsumption: true,
    monthlyConsumptionReason: 'Skincare routine staple',
    estimatedCLV: 120,
    estimatedCAC: 20,
    monthlyChurnPercent: 25,
    marketSizeNL: '3M+ Target Demo',
    marketSizeScore: 90,
    acquisitionDifficulty: 'Easy',
    emotionalLoyalty: 'High',
    storyDepth: 7,
    brandType: 'Aesthetic-Pleasure',
    microNichePotential: 6,
    awarenessLevel: 'Solution-aware',
    status: 'Shortlisted',
    lastUpdated: new Date().toISOString(),
    notes: 'Low CAC via TikTok organic possible. People switch products often though (high churn).'
  },
  {
    id: '5',
    name: 'Specialty Coffee Beans Subscription',
    targetAudience: 'Coffee Enthusiasts',
    realMonthlyConsumption: true,
    monthlyConsumptionReason: 'Daily consumption staple',
    estimatedCLV: 200,
    estimatedCAC: 30,
    monthlyChurnPercent: 10,
    marketSizeNL: '4M+ Daily Drinkers',
    marketSizeScore: 85,
    acquisitionDifficulty: 'Medium',
    emotionalLoyalty: 'High',
    storyDepth: 9,
    brandType: 'Aesthetic-Pleasure',
    microNichePotential: 7,
    awarenessLevel: 'Product-aware',
    status: 'Shortlisted',
    lastUpdated: new Date().toISOString(),
    notes: 'Great retention if the coffee is truly excellent. Margins can be tricky with shipping.'
  },
  {
    id: '6',
    name: 'Adaptogen Drink Powder',
    targetAudience: 'Stressed Professionals 30-50',
    realMonthlyConsumption: true,
    monthlyConsumptionReason: 'Evening wind-down ritual',
    estimatedCLV: 150,
    estimatedCAC: 40,
    monthlyChurnPercent: 20,
    marketSizeNL: '1M Target Demo',
    marketSizeScore: 50,
    acquisitionDifficulty: 'Medium',
    emotionalLoyalty: 'Medium',
    storyDepth: 6,
    brandType: 'Solution-based',
    microNichePotential: 6,
    awarenessLevel: 'Problem-aware',
    status: 'Researching',
    lastUpdated: new Date().toISOString(),
    notes: 'Requires education on what adaptogens actually do. Tastes need to be masked.'
  },
  {
    id: '7',
    name: 'Collagen Peptides Powder',
    targetAudience: 'Women 35+',
    realMonthlyConsumption: true,
    monthlyConsumptionReason: 'Anti-aging daily supplement',
    estimatedCLV: 280,
    estimatedCAC: 60,
    monthlyChurnPercent: 15,
    marketSizeNL: '2M Target Demo',
    marketSizeScore: 70,
    acquisitionDifficulty: 'Hard',
    emotionalLoyalty: 'Medium',
    storyDepth: 4,
    brandType: 'Solution-based',
    microNichePotential: 4,
    awarenessLevel: 'Product-aware',
    status: 'Researching',
    lastUpdated: new Date().toISOString(),
    notes: 'Commoditized space. Need a unique angle or delivery mechanism (e.g. liquid collagen).'
  },
  {
    id: '8',
    name: 'Testosterone Support Coffee (Men)',
    targetAudience: 'Men 35-55 (Fitness conscious)',
    realMonthlyConsumption: true,
    monthlyConsumptionReason: 'Morning energy + hormone support',
    estimatedCLV: 220,
    estimatedCAC: 50,
    monthlyChurnPercent: 18,
    marketSizeNL: '800k Target Demo',
    marketSizeScore: 45,
    acquisitionDifficulty: 'Medium',
    emotionalLoyalty: 'High',
    storyDepth: 8,
    brandType: 'Solution-based',
    microNichePotential: 9,
    awarenessLevel: 'Problem-aware',
    status: 'Shortlisted',
    lastUpdated: new Date().toISOString(),
    notes: 'Strong angle. Men are highly motivated to solve this pain point. High niche potential.'
  }
];
